spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

mybatis:
  configuration:
    map-underscore-to-camel-case: true

aliyun:
    oss:
      access-key-id: ${ALI_ACCESS_KEY_ID}
      access-key-secret: ${ALI_ACCESS_KEY_SECRET}
      endpoint: oss-cn-beijing.aliyuncs.com
      bucket: repair-system-demo

logging:
  file:
    name: ./week02/project/repair-system/logs/app.log